kafka_rest_jolokia_java_arg: "-javaagent:{{jolokia_jar_path}}=port={{kafka_rest_jolokia_port}},host=0.0.0.0"
kafka_rest_open_file_limit: "{{open_file_limit}}"
kafka_rest_service_overrides:
  LimitNOFILE: "{{kafka_rest_open_file_limit}}"
kafka_rest_service_environment_overrides:
  LOG_DIR: /var/log/kafka-rest
  KAFKAREST_OPTS: "{{kafka_rest_jolokia_java_arg}}"

kafka_rest_packages:
  - confluent-kafka-rest

kafka_rest:
  user: cp-kafka-rest
  group: confluent
  config_file: /etc/kafka-rest/kafka-rest.properties
  service_name: confluent-kafka-rest
  systemd_file: /usr/lib/systemd/system/confluent-kafka-rest.service
  systemd_override: /etc/systemd/system/confluent-kafka-rest.service.d
  properties:
    listeners: http://0.0.0.0:8082
    client.ssl.endpoint.identification.algorithm: ""
  systemd:
    enabled: yes
    state: started
