control_center_open_file_limit: "{{open_file_limit}}"
control_center_service_overrides:
  LimitNOFILE: "{{control_center_open_file_limit}}"
control_center_service_environment_overrides:
  CONTROL_CENTER_HEAP_OPTS: "-Xmx6g"

control_center_packages:
  - confluent-control-center
  - confluent-control-center-fe


control_center:
  user: cp-control-center
  group: confluent
  config_file: /etc/confluent-control-center/control-center-production.properties
  systemd_file: /usr/lib/systemd/system/confluent-control-center.service
  systemd_override: /etc/systemd/system/confluent-control-center.service.d
  service_name: confluent-control-center
  properties:
    confluent.controlcenter.streams.num.stream.threads: 8
    confluent.controlcenter.data.dir: /var/lib/confluent/control-center
    confluent.controlcenter.ksql.enable: 'true'
    confluent.controlcenter.schema.registry.enable: 'true'
    confluent.controlcenter.streams.ssl.endpoint.identification.algorithm: ""
    confluent.controlcenter.rest.ssl.endpoint.identification.algorithm: ""
  systemd:
    enabled: yes
    state: started
