---
  dependencies:
    - { role: nginx, nginx_server_root: /var/www/html/wordpress, nginx_php_enabled: true, tags: wordpress }
    - { role: mysql, when: wordpress_mysql_enabled, mysql_socket_enabled: false, tags: wordpress }
