---
dependency:
  name: galaxy
driver:
  name: ec2
lint:
  name: yamllint
platforms:
  - name: molecule-rabbitmq-${TEST_DISTRO:-ubuntu1804}-${TEST_INSTANCE_NAME:-1}
    distro: ${TEST_DISTRO:-ubuntu1804}
provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        rabbitmq_erlang_cookie: FAKECOOKIEFORMOLECULETESTS
  options:
    diff: ${TEST_ENABLE_ANSIBLE_DIFF:-true}
    v: ${TEST_ENABLE_ANSIBLE_VERBOSITY:-false}
  config_options:
    defaults:
      stdout_callback: yaml
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: goss
  lint:
    name: yamllint
  env:
    TEST_DISTRO: ${TEST_DISTRO:-ubuntu1804}
