---

wildfly_version: 10.1.0.Final
wildfly_url: http://download.jboss.org/wildfly/{{ wildfly_version }}/wildfly-{{ wildfly_version }}.zip
wildfly_dest: /opt

wildfly_user: wildfly
wildfly_group: "{{ wildfly_user }}"

wildfly_webapps_path: /webapps
