---

  - name: Installing logrotate
    package:
      name: logrotate
      state: present
    tags: logrotate

  - name: 'Copy the logrotate template to /etc/logrotate.d'
    template:
     src: logrotate.d.j2
     dest: /etc/logrotate.d/log_batata
     owner: root
     group: root
