- name: create ssl certificate directory
  file:
    path: /var/ssl/private
    state: directory
    mode: 0755
- name: copy ca certs to host
  copy:
    src: "{{ssl_ca_certificate_path}}"
    dest: /var/ssl/private
    mode: 0755
- name: copy host certs to host
  copy:
    src: "{{ssl_host_key_path}}"
    dest: /var/ssl/private
    mode: 0755
- name: copy private key to host
  copy:
    src: "{{ssl_private_key_path}}"
    dest: /var/ssl/private
    mode: 0755
- name: copy ssl script to host
  copy:
    src: scripts/certs-import.sh
    dest: /var/ssl/private
    mode: 0755
- name: Import SSL Certs
  shell: /var/ssl/private/certs-import.sh "{{ssl_ca_certificate}}" "{{ssl_host_key}}" "{{ssl_private_key}}" "{{host_keystore_storepass}}" "{{host_truststore_storepass}}" "{{ca_cert_password}}" "{{host_cert_password}}" "{{privatekey_keystore_password}}" 
  args:
    chdir: /var/ssl/private
    creates: /var/ssl/private/broker.keystore.jks
- name: copy ssl related files to local ansible host
  synchronize:
    src: /var/ssl/private/
    dest: generated_ssl_files
    mode: pull

