---
# defaults file for app_php

app_path: /data
app_repository: https://github.com/blongden/phpinfo.git

app_user: deploy
app_group: "{{ app_user }}"

app_shared_folders:
  - "{{ app_path }}"
  - "{{ app_path }}/.ssh"
  - "{{ app_path }}/shared"
  - "{{ app_path }}/logs"

app_base_packages:
  - git
  - sudo

app_config:
  DISTRO: linux
