# -*- mode: ruby -*-
# vi: set ft=ruby :

BOX_MEM = ENV['BOX_MEM'] || "1024"
BOX_NAME = ENV['BOX_NAME'] || "ubuntu/xenial64"

Vagrant.configure("2") do |config|

config.vm.define :nfsserver do |nfsserver|
	nfsserver.vm.box = BOX_NAME
	nfsserver.vm.hostname = "nfsserver.local"
	nfsserver.vm.network "private_network", ip: "192.168.50.4"
	nfsserver.vm.provider "virtualbox" do |vb|
		vb.memory = 2048
	end
	
nfsserver.vm.provision "ansible" do |ansible|
	ansible.playbook = "/home/leodb/Desktop/gitsky/iaas/ansible/nfs_server.yml"
	end
	end

end
