---
- name: Create configuration files
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: rabbitmq
    mode: 0664
  loop:
    - src: rabbitmq.conf.j2
      dest: /etc/rabbitmq/rabbitmq.conf
    - src: rabbitmq-env.conf.j2
      dest: /etc/rabbitmq/rabbitmq-env.conf
  notify: Restart RabbitMQ Server

- name: Ensure selected plugins are enabled
  template:
    src: enabled_plugins.j2
    dest: /etc/rabbitmq/enabled_plugins
    owner: root
    group: rabbitmq
    mode: 0664
  notify: Restart RabbitMQ Server
