---

  - name: Enable IUS
    yum:
      name: https://centos7.iuscommunity.org/ius-release.rpm
    when:
      ansible_os_family == "RedHat"
    tags: python

  - name: Install Python{{ python_version }}
    yum:
      name: "{{ item }}"
      state: latest
    with_items:
      - "{{ packages[ansible_os_family + '-python' + centos_python_version] }}"
    when:
      ansible_os_family == "RedHat"
    tags: python
