---
- include_tasks: setup-RedHat.yml
  when: ansible_os_family == "RedHat"
  tags: elasticsearch:setup

- include_tasks: setup-Debian.yml
  when: ansible_os_family == "Debian"
  tags: elasticsearch:setup

- name: Install Elasticsearch
  package:
    name: elasticsearch
    state: "{{ elasticsearch_package_state }}"
  tags: elasticsearch:packages

- name: Ensure data directory exists
  file:
    path: "{{ elasticsearch_path_data }}"
    state: directory
    owner: elasticsearch
    group: elasticsearch
    mode: 0750
  tags: elasticsearch:configure

- name: Configure Elasticsearch
  template:
    src: elasticsearch.yml.j2
    dest: /etc/elasticsearch/elasticsearch.yml
    owner: root
    group: elasticsearch
    mode: 0660
  notify: Restart Elasticsearch
  tags: elasticsearch:configure

- name: Force a restart if configuration has changed
  meta: flush_handlers
  tags: elasticsearch:configure

- name: Start Elasticsearch
  service:
    name: elasticsearch
    state: "{{ elasticsearch_service_state }}"
    enabled: "{{ elasticsearch_service_enabled }}"
  tags: elasticsearch:service

- name: Ensure Elasticsearch is running before proceeding
  wait_for:
    host: "{{ elasticsearch_network_host }}"
    port: "{{ elasticsearch_http_port }}"
    delay: 3
    timeout: 300
  tags: elasticsearch:test
