---
  - name: start kubelet
    service:
      name: kubelet
      state: started
      enabled: yes
      daemon_reload: yes
      
  - name: restart kubelet
    service:
      name: kubelet
      state: restarted
      enabled: yes
      daemon_reload: yes