---
# handlers file for supervisord

- name: restart supervisord
  service:
    name: "{{ (ansible_os_family == 'Debian') | ternary('supervisor', 'supervisord') }}"
    enabled: yes
    state: restarted
