---
  - name: restart Squid
    service:
      name: squid
      state: restarted
      enabled: yes
    when:
      ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"
    tags: squid

  - name: Restart squid
    systemd:
      name: squid
      state: restarted
    when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7" or ansible_distribution == "OracleLinux"
    tags: Squid
