---
extends: default

ignore: |
  .gitlab-ci.yml
  .pre-commit-config.yaml

rules:
  braces:
    max-spaces-inside: 1
    level: error
  brackets:
    max-spaces-inside: 1
    level: error
  line-length:
    max: 120
    level: warning
  new-line-at-end-of-file: enable
