---
# tasks file for app_java

  - name: Install base packages
    package:
      name: "{{ item }}"
      state: latest
    with_items:
      - "{{ app_base_packages }}"
    tags:
      - app_java
      - deploy

  - name: Create {{ app_group }} group
    group:
      name: "{{ app_group }}"
      state: present
    tags:
      - app_java
      - deploy

  - name: Create {{ app_user }} username
    user:
      name: "{{ app_user }}"
      group: "{{ app_group }}"
      createhome: no
      home: "{{ app_path }}"
      shell: /bin/bash
    tags:
      - app_java
      - deploy

  - name: Create base directories
    file:
      path: "{{ item }}"
      state: directory
      owner: "{{ app_user }}"
      group: "{{ app_group }}"
    with_items:
      - "{{ app_shared_folders }}"
    tags:
      - app_java
      - deploy

  - name: Check if client key exists
    stat:
      path: /etc/.client_key
    register: client_key
    tags:
      - app_java
      - deploy

  - name: Enable client key for repository
    file:
      src: /etc/.client_key
      dest: "{{ app_path }}/.ssh/id_rsa"
      state: link
      owner: "{{ app_user }}"
      group: "{{ app_group }}"
    when: client_key.stat.exists == True
    tags:
      - app_java
      - deploy

  - name: Install application
    get_url:
      url: "{{ app_artifact }}"
      dest: "{{ app_path }}/app/{{ app_artifact | basename }}"
      owner: "{{ app_user }}"
      group: "{{ app_group }}"
    tags:
      - app_java
      - deploy
