---

- name: "Graylog repository package should be downloaded"
  get_url:
    url: "{{ graylog_apt_deb_url }}"
    dest: "/tmp/graylog_repository.deb"
  when: graylog_manage_apt_repo

- name: "Package 'apt-transport-https' should be installed"
  apt:
    name: "apt-transport-https"
    state: "installed"

- name: "Graylog repository package should be installed"
  apt:
    deb: "/tmp/graylog_repository.deb"
    state: "installed"
    dpkg_options: "force-all"
  when: graylog_manage_apt_repo
  register: "install_repo"

- name: "APT cache should be updated"
  apt:
    update_cache: True
  when: install_repo.changed

- name: "Graylog server package should be installed"
  apt:
    name: "graylog-server{% if graylog_server_version is defined %}={{ graylog_server_version }}{% endif %}"
    state: "{{ graylog_package_state }}"
  notify: "restart graylog-server"
