---

  service:
    sonarqube:
      running: true
      enabled: true

  port:
    tcp:9000:
      listening: true
      ip:
        - 0.0.0.0

  file:
    /opt/sonarqube/conf/sonar.properties:
      exists: true
    /etc/init.d/sonarqube:
      exists: true
