---
  version: '2'
  services:
    centos6:
      image: deadc/ansible_centos6
      cap_add:
        - NET_ADMIN
        - SYS_ADMIN
        - SYS_NICE
        - SYS_RESOURCE
        - SYS_TIME
      security_opt:
        - seccomp:unconfined
      volumes:
        - /sys/fs/cgroup:/sys/fs/cgroup:ro
        - .:/ansible/roles/test

    centos7:
      image: deadc/ansible_centos7
      cap_add:
        - NET_ADMIN
        - SYS_ADMIN
        - SYS_NICE
        - SYS_RESOURCE
        - SYS_TIME
      security_opt:
        - seccomp:unconfined
      volumes:
        - /sys/fs/cgroup:/sys/fs/cgroup:ro
        - .:/ansible/roles/test

    debian9:
      image: deadc/ansible_debian9
      cap_add:
        - NET_ADMIN
        - SYS_ADMIN
        - SYS_NICE
        - SYS_RESOURCE
        - SYS_TIME
      security_opt:
        - seccomp:unconfined
      volumes:
        - /sys/fs/cgroup:/sys/fs/cgroup:ro
        - .:/ansible/roles/test

    amazonlinux2:
      image: guipedreira/amazonlinux2
      cap_add:
        - NET_ADMIN
        - SYS_ADMIN
        - SYS_NICE
        - SYS_RESOURCE
        - SYS_TIME
      security_opt:
        - seccomp:unconfined
      volumes:
        - /sys/fs/cgroup:/sys/fs/cgroup:ro
        - .:/ansible/roles/test
    amazonlinux:
      image: guipedreira/amazonlinux1
      cap_add:
        - NET_ADMIN
        - SYS_ADMIN
        - SYS_NICE
        - SYS_RESOURCE
        - SYS_TIME
      security_opt:
        - seccomp:unconfined
      volumes:
        - /sys/fs/cgroup:/sys/fs/cgroup:ro
        - .:/ansible/roles/test
...