---
  version: '2'
  services:
    centos7:
      image: deadc/ansible_centos7
      cap_add:
        - NET_ADMIN
        - SYS_ADMIN
      security_opt:
        - seccomp:unconfined
      volumes:
        - /sys/fs/cgroup:/sys/fs/cgroup:ro
        - .:/ansible/roles/test
      devices:
        - /dev/net/tun:/dev/net/tun
      # sysctls:
      #   net.ipv6.conf.all.disable_ipv6: 1
      #   net.ipv4.ip_forward: 1


    debian9:
      image: deadc/ansible_debian9
      cap_add:
        - NET_ADMIN
        - SYS_ADMIN
      security_opt:
        - seccomp:unconfined
      volumes:
        - /sys/fs/cgroup:/sys/fs/cgroup:ro
        - .:/ansible/roles/test
      devices:
        - /dev/net/tun:/dev/net/tun
      # sysctls:
      #   net.ipv6.conf.all.disable_ipv6: 1
      #   net.ipv4.ip_forward: 1
