---

  file:
    /etc/localtime:
      exists: true
      filetype: symlink
      linked-to: /usr/share/zoneinfo/America/Sao_Paulo

  package:
    {{ if eq .Vars.ansible_facts.ansible_distribution "CentOS" }}
    epel-release:
      installed: true
    {{ end }}
    htop:
      installed: true
    git:
      installed: true
    sysstat:
      installed: true
    telnet:
      installed: true
