---
  version: '2'
  services:
    centos6:
      image: deadc/docker-ansible-centos6
      cap_add:
        - SYS_ADMIN
        - IPC_LOCK
      security_opt:
        - seccomp:unconfined
      volumes:
        - /sys/fs/cgroup:/sys/fs/cgroup:ro
        - .:/ansible/roles/test

    centos7:
      image: deadc/docker-ansible-centos7
      cap_add:
        - SYS_ADMIN
        - IPC_LOCK
      security_opt:
        - seccomp:unconfined
      volumes:
        - /sys/fs/cgroup:/sys/fs/cgroup:ro
        - .:/ansible/roles/test

    debian9:
      image: deadc/docker-ansible-debian9
      cap_add:
        - SYS_ADMIN
        - IPC_LOCK
      security_opt:
        - seccomp:unconfined
      volumes:
        - /sys/fs/cgroup:/sys/fs/cgroup:ro
        - .:/ansible/roles/test
