---
# defaults file for pyenv

# pip only exists starting from 2.7.9
pyenv_python_version: 2.7.9

pyenv_repository: https://github.com/pyenv/pyenv.git
pyenv_path: /data/shared


packages:
  RedHat:
    - git
    - patch
    - gcc
    - zlib-devel
    - bzip2
    - bzip2-devel
    - readline-devel
    - sqlite
    - sqlite-devel
    - openssl-devel
    - xz
    - xz-devel
  Debian:
    - git
    - build-essential
    - libssl1.0-dev
    - zlib1g-dev
    - libbz2-dev
    - libreadline-dev
    - libsqlite3-dev
    - wget
    - curl
    - llvm
    - libncurses5-dev
    - libncursesw5-dev
    - xz-utils
    - tk-dev
