---
# vars file for ansible-prometheus
prometheus_archive: "prometheus-{{ prometheus_version }}.{{ prometheus_platform_architecture }}"
prometheus_tarball_url: "https://github.com/prometheus/prometheus/releases/download/v{{ prometheus_version }}/{{ prometheus_archive }}.tar.gz"

prometheus_node_exporter_archive: "node_exporter-{{ prometheus_node_exporter_version }}.{{ prometheus_platform_architecture }}"
prometheus_node_exporter_tarball_url: "https://github.com/prometheus/node_exporter/releases/download/v{{ prometheus_node_exporter_version }}/{{ prometheus_node_exporter_archive }}.tar.gz"

prometheus_alert_manager_archive: "alertmanager-{{ prometheus_alert_manager_version }}.{{ prometheus_platform_architecture }}"
prometheus_alert_manager_tarball_url: "https://github.com/prometheus/alertmanager/releases/download/v{{ prometheus_alert_manager_version }}/{{ prometheus_alert_manager_archive }}.tar.gz"
